import type { RoleFamily } from "@/types/career";
import { independentWorkRoles } from "@/lib/independent-work-intelligence";

export type CareerTarget = {
  title: string;
  roleFamily: RoleFamily;
  aliases?: string[];
};

const groupedCareerTargets: Record<RoleFamily, CareerTarget[]> = {
  "Customer Success": [
    { title: "Customer Support", roleFamily: "Customer Success", aliases: ["customer support associate", "customer support representative"] },
    { title: "Client Support", roleFamily: "Customer Success", aliases: ["client support associate", "client support representative"] },
    { title: "Customer Success Associate", roleFamily: "Customer Success", aliases: ["customer success specialist", "client success representative"] },
    { title: "Customer Success Specialist", roleFamily: "Customer Success" },
    { title: "Customer Support Specialist", roleFamily: "Customer Success" },
    { title: "Customer Experience Associate", roleFamily: "Customer Success" },
    { title: "Customer Experience Specialist", roleFamily: "Customer Success" },
    { title: "Client Services Associate", roleFamily: "Customer Success" },
    { title: "Client Services Coordinator", roleFamily: "Customer Success" },
    { title: "Member Services Representative", roleFamily: "Customer Success" },
    { title: "Onboarding Specialist", roleFamily: "Customer Success" },
    { title: "Account Coordinator", roleFamily: "Customer Success" },
    { title: "Support Specialist", roleFamily: "Customer Success" },
    { title: "Customer Care Specialist", roleFamily: "Customer Success" },
    { title: "Client Support Representative", roleFamily: "Customer Success" },
    { title: "Customer Care Coordinator", roleFamily: "Customer Success" },
    { title: "Customer Service Coordinator", roleFamily: "Customer Success" },
    { title: "Customer Service Specialist", roleFamily: "Customer Success" },
    { title: "Client Success Associate", roleFamily: "Customer Success" },
    { title: "Client Success Coordinator", roleFamily: "Customer Success" },
    { title: "Customer Operations Associate", roleFamily: "Customer Success" },
    { title: "Customer Retention Associate", roleFamily: "Customer Success" },
    { title: "Account Support Associate", roleFamily: "Customer Success" },
    { title: "Implementation Support Specialist", roleFamily: "Customer Success" },
    { title: "Community Support Specialist", roleFamily: "Customer Success" },
    { title: "User Support Associate", roleFamily: "Customer Success" }
  ],
  Operations: [
    { title: "Operations Associate", roleFamily: "Operations" },
    { title: "Operations Coordinator", roleFamily: "Operations" },
    { title: "Business Operations Associate", roleFamily: "Operations" },
    { title: "Warehouse Associate", roleFamily: "Operations", aliases: ["warehouse worker", "stock associate"] },
    { title: "Inventory Associate", roleFamily: "Operations", aliases: ["inventory support", "stock support"] },
    { title: "Fulfillment Associate", roleFamily: "Operations", aliases: ["order fulfillment", "fulfillment support"] },
    { title: "Logistics Support", roleFamily: "Operations", aliases: ["logistics assistant", "logistics support associate"] },
    { title: "Dispatch Assistant", roleFamily: "Operations", aliases: ["dispatch support", "route support"] },
    { title: "Facilities Assistant", roleFamily: "Operations", aliases: ["facilities support", "building support"] },
    { title: "Maintenance Assistant", roleFamily: "Operations", aliases: ["maintenance support", "repair support"] },
    { title: "Building Operations Support", roleFamily: "Operations", aliases: ["building operations assistant", "facilities operations support"] },
    { title: "Appointment Coordinator", roleFamily: "Operations", aliases: ["appointment scheduler", "booking coordinator"] },
    { title: "Field Associate", roleFamily: "Operations", aliases: ["field support", "field operations support"] },
    { title: "Logistics Coordinator", roleFamily: "Operations" },
    { title: "Fulfillment Coordinator", roleFamily: "Operations" },
    { title: "Warehouse Operations Coordinator", roleFamily: "Operations" },
    { title: "Workforce Coordinator", roleFamily: "Operations" },
    { title: "Scheduling Coordinator", roleFamily: "Operations" },
    { title: "Process Coordinator", roleFamily: "Operations" },
    { title: "Inventory Coordinator", roleFamily: "Operations" },
    { title: "Service Operations Associate", roleFamily: "Operations" },
    { title: "Retail Operations Associate", roleFamily: "Operations" },
    { title: "Facilities Coordinator", roleFamily: "Operations" },
    { title: "Inventory Control Associate", roleFamily: "Operations" },
    { title: "Supply Chain Coordinator", roleFamily: "Operations" },
    { title: "Dispatch Coordinator", roleFamily: "Operations" },
    { title: "Route Coordinator", roleFamily: "Operations" },
    { title: "Production Coordinator", roleFamily: "Operations" },
    { title: "Quality Coordinator", roleFamily: "Operations" },
    { title: "Field Operations Associate", roleFamily: "Operations" },
    { title: "Store Operations Coordinator", roleFamily: "Operations" },
    { title: "Shipping Coordinator", roleFamily: "Operations" },
    { title: "Receiving Coordinator", roleFamily: "Operations" },
    { title: "Operations Support Specialist", roleFamily: "Operations" }
  ],
  Admin: [
    { title: "Administrative Assistant", roleFamily: "Admin" },
    { title: "Administrative Coordinator", roleFamily: "Admin" },
    { title: "Office Coordinator", roleFamily: "Admin" },
    { title: "Front Desk Coordinator", roleFamily: "Admin" },
    { title: "Receptionist", roleFamily: "Admin" },
    { title: "Executive Assistant", roleFamily: "Admin" },
    { title: "Records Coordinator", roleFamily: "Admin" },
    { title: "Data Entry Specialist", roleFamily: "Admin" },
    { title: "Office Assistant", roleFamily: "Admin" },
    { title: "Program Assistant", roleFamily: "Admin" },
    { title: "Operations Assistant", roleFamily: "Admin" },
    { title: "Scheduling Assistant", roleFamily: "Admin" },
    { title: "Administrative Support Specialist", roleFamily: "Admin" },
    { title: "Office Administrator", roleFamily: "Admin" },
    { title: "Clerical Assistant", roleFamily: "Admin" },
    { title: "Records Assistant", roleFamily: "Admin" },
    { title: "Document Control Assistant", roleFamily: "Admin" },
    { title: "Office Support Specialist", roleFamily: "Admin" },
    { title: "Department Assistant", roleFamily: "Admin" },
    { title: "Team Assistant", roleFamily: "Admin" },
    { title: "Patient Access Representative", roleFamily: "Admin" },
    { title: "Patient Services Representative", roleFamily: "Admin", aliases: ["patient support representative", "patient services associate"] },
    { title: "Healthcare Admin Assistant", roleFamily: "Admin", aliases: ["healthcare administrative assistant", "medical office assistant"] },
    { title: "Unit Secretary", roleFamily: "Admin" },
    { title: "Mailroom Coordinator", roleFamily: "Admin" },
    { title: "Virtual Assistant", roleFamily: "Admin" }
  ],
  Sales: [
    { title: "Sales Development Representative", roleFamily: "Sales" },
    { title: "Business Development Representative", roleFamily: "Sales" },
    { title: "Sales Coordinator", roleFamily: "Sales" },
    { title: "Account Representative", roleFamily: "Sales" },
    { title: "Inside Sales Representative", roleFamily: "Sales" },
    { title: "Lead Generation Specialist", roleFamily: "Sales" },
    { title: "Account Associate", roleFamily: "Sales" },
    { title: "Sales Support Specialist", roleFamily: "Sales" },
    { title: "Client Relations Associate", roleFamily: "Sales" },
    { title: "Retail Sales Associate", roleFamily: "Sales" },
    { title: "Territory Sales Associate", roleFamily: "Sales" },
    { title: "Account Development Representative", roleFamily: "Sales" },
    { title: "Sales Operations Associate", roleFamily: "Sales" },
    { title: "Sales Assistant", roleFamily: "Sales" },
    { title: "Partnerships Associate", roleFamily: "Sales" },
    { title: "Market Development Representative", roleFamily: "Sales" },
    { title: "Enrollment Advisor", roleFamily: "Sales" },
    { title: "Admissions Representative", roleFamily: "Sales" },
    { title: "Leasing Consultant", roleFamily: "Sales" },
    { title: "Customer Account Representative", roleFamily: "Sales" },
    { title: "Business Development Associate", roleFamily: "Sales" },
    { title: "Account Services Associate", roleFamily: "Sales" },
    { title: "Channel Sales Associate", roleFamily: "Sales" },
    { title: "Sales Enablement Coordinator", roleFamily: "Sales" }
  ],
  Business: [
    { title: "Business Analyst", roleFamily: "Business" },
    { title: "Junior Business Analyst", roleFamily: "Business" },
    { title: "Business Operations Associate", roleFamily: "Business" },
    { title: "Operations Analyst", roleFamily: "Business" },
    { title: "Process Analyst", roleFamily: "Business" },
    { title: "Strategy Associate", roleFamily: "Business" },
    { title: "Program Associate", roleFamily: "Business" },
    { title: "Reporting Analyst", roleFamily: "Business" },
    { title: "Data Analyst Associate", roleFamily: "Business" },
    { title: "Business Support Specialist", roleFamily: "Business" },
    { title: "Research Associate", roleFamily: "Business" },
    { title: "Business Coordinator", roleFamily: "Business" },
    { title: "Process Improvement Associate", roleFamily: "Business" },
    { title: "Operations Reporting Associate", roleFamily: "Business" },
    { title: "Business Intelligence Associate", roleFamily: "Business" },
    { title: "Market Research Associate", roleFamily: "Business" },
    { title: "Compliance Analyst Associate", roleFamily: "Business" },
    { title: "Compliance Assistant", roleFamily: "Business", aliases: ["compliance support", "compliance support assistant"] },
    { title: "Risk Operations Associate", roleFamily: "Business" },
    { title: "Vendor Management Associate", roleFamily: "Business" },
    { title: "Procurement Associate", roleFamily: "Business" },
    { title: "Finance Operations Associate", roleFamily: "Business" },
    { title: "People Operations Associate", roleFamily: "Business" },
    { title: "Revenue Operations Associate", roleFamily: "Business" },
    { title: "Data Quality Analyst", roleFamily: "Business" }
  ],
  "Project Coordination": [
    { title: "Project Coordinator", roleFamily: "Project Coordination" },
    { title: "Project Administrator", roleFamily: "Project Coordination" },
    { title: "Program Coordinator", roleFamily: "Project Coordination" },
    { title: "Implementation Coordinator", roleFamily: "Project Coordination" },
    { title: "PMO Coordinator", roleFamily: "Project Coordination" },
    { title: "Project Support Specialist", roleFamily: "Project Coordination" },
    { title: "Delivery Coordinator", roleFamily: "Project Coordination" },
    { title: "Operations Project Coordinator", roleFamily: "Project Coordination" },
    { title: "Client Implementation Coordinator", roleFamily: "Project Coordination" },
    { title: "Project Assistant", roleFamily: "Project Coordination" },
    { title: "Implementation Associate", roleFamily: "Project Coordination" },
    { title: "Project Scheduler", roleFamily: "Project Coordination" },
    { title: "Project Controls Assistant", roleFamily: "Project Coordination" },
    { title: "Creative Project Coordinator", roleFamily: "Project Coordination" },
    { title: "Marketing Project Coordinator", roleFamily: "Project Coordination" },
    { title: "IT Project Coordinator", roleFamily: "Project Coordination" },
    { title: "Construction Project Coordinator", roleFamily: "Project Coordination" },
    { title: "Clinical Project Coordinator", roleFamily: "Project Coordination" },
    { title: "Training Coordinator", roleFamily: "Project Coordination" },
    { title: "Event Project Coordinator", roleFamily: "Project Coordination" },
    { title: "Rollout Coordinator", roleFamily: "Project Coordination" },
    { title: "Delivery Associate", roleFamily: "Project Coordination" },
    { title: "Client Project Associate", roleFamily: "Project Coordination" },
    { title: "Program Assistant", roleFamily: "Project Coordination" }
  ],
  "IT Support": [
    { title: "Help Desk Technician", roleFamily: "IT Support" },
    { title: "IT Support Specialist", roleFamily: "IT Support" },
    { title: "IT Support Trainee", roleFamily: "IT Support", aliases: ["tech support trainee", "technical support trainee"] },
    { title: "Technical Support Representative", roleFamily: "IT Support" },
    { title: "Desktop Support Technician", roleFamily: "IT Support" },
    { title: "Service Desk Analyst", roleFamily: "IT Support" },
    { title: "Support Technician", roleFamily: "IT Support" },
    { title: "Field Support Technician", roleFamily: "IT Support" },
    { title: "IT Coordinator", roleFamily: "IT Support" },
    { title: "Systems Support Associate", roleFamily: "IT Support" },
    { title: "User Support Specialist", roleFamily: "IT Support" },
    { title: "Help Desk Analyst", roleFamily: "IT Support" },
    { title: "IT Support Technician", roleFamily: "IT Support" },
    { title: "Technical Help Desk Associate", roleFamily: "IT Support" },
    { title: "Computer Support Specialist", roleFamily: "IT Support" },
    { title: "Device Support Technician", roleFamily: "IT Support" },
    { title: "Network Support Technician", roleFamily: "IT Support" },
    { title: "Application Support Analyst", roleFamily: "IT Support" },
    { title: "IT Service Desk Technician", roleFamily: "IT Support" },
    { title: "End User Support Technician", roleFamily: "IT Support" },
    { title: "Technical Customer Support Specialist", roleFamily: "IT Support" },
    { title: "IT Operations Associate", roleFamily: "IT Support" },
    { title: "Systems Technician", roleFamily: "IT Support" },
    { title: "Junior Systems Administrator", roleFamily: "IT Support" },
    { title: "Support Desk Coordinator", roleFamily: "IT Support" }
  ],
  Tech: [
    { title: "QA Tester", roleFamily: "Tech" },
    { title: "Junior QA Analyst", roleFamily: "Tech" },
    { title: "Manual QA Tester", roleFamily: "Tech" },
    { title: "Product Operations Associate", roleFamily: "Tech" },
    { title: "Technical Operations Associate", roleFamily: "Tech" },
    { title: "Implementation Specialist", roleFamily: "Tech" },
    { title: "Data Associate", roleFamily: "Tech" },
    { title: "Product Support Specialist", roleFamily: "Tech" },
    { title: "Junior Product Analyst", roleFamily: "Tech" },
    { title: "Technical Support Specialist", roleFamily: "Tech" },
    { title: "Software Support Specialist", roleFamily: "Tech" },
    { title: "Web Support Specialist", roleFamily: "Tech" },
    { title: "Implementation Associate", roleFamily: "Tech" },
    { title: "Product Analyst Associate", roleFamily: "Tech" },
    { title: "Data Operations Associate", roleFamily: "Tech" },
    { title: "QA Coordinator", roleFamily: "Tech" },
    { title: "Test Analyst", roleFamily: "Tech" },
    { title: "Release Coordinator", roleFamily: "Tech" },
    { title: "Product Coordinator", roleFamily: "Tech" },
    { title: "Technical Project Assistant", roleFamily: "Tech" },
    { title: "Junior Data Analyst", roleFamily: "Tech" },
    { title: "Support Engineer Associate", roleFamily: "Tech" },
    { title: "Customer Technical Support Associate", roleFamily: "Tech" },
    { title: "Technical Implementation Coordinator", roleFamily: "Tech" }
  ],
  Security: [
    { title: "Security Officer", roleFamily: "Security" },
    { title: "Security Guard", roleFamily: "Security" },
    { title: "Public Safety Officer", roleFamily: "Security" },
    { title: "Access Control Specialist", roleFamily: "Security" },
    { title: "Surveillance Operator", roleFamily: "Security" },
    { title: "Loss Prevention Associate", roleFamily: "Security" },
    { title: "Asset Protection Associate", roleFamily: "Security" },
    { title: "Campus Safety Officer", roleFamily: "Security" }
  ]
};

export const careerTargets: CareerTarget[] = [...Object.values(groupedCareerTargets).flat(), ...independentWorkRoles];
