// GENERATED by scripts/compute-surface-hash.mjs — do not edit by hand.
//
// Fingerprint of the checkout/webhook/license/storage/package code that an
// operational certification vouches for. If this changes, prior proof is void
// and checkout re-closes until the journey is certified again.

export const CERTIFIED_SURFACE_HASH = "391520d4af8c4bc7d9a625c31926b15c";
