// GENERATED by scripts/compute-surface-hash.mjs — do not edit by hand.
//
// Fingerprint of the checkout/webhook/license/storage/package code that an
// operational certification vouches for. If this changes, prior proof is void
// and checkout re-closes until the journey is certified again.

export const CERTIFIED_SURFACE_HASH = "bf2b361d3a9c4072c8c3b340ea7fc1f2";
